### ISSUE TITLE
Which versions to submit to DefinitelyTyped?

### ISSUE THREAD

**Issue by ringods** [JimDanner/definitelytyped-thunderbird-webext-browser#1]
Hello @JimDanner, thanks for enabling Github issues here.

I retried your tool on v115 with the latest fixes you made and it works indeed. As a newcomer to the any development of extensions for Firefox or Thunderbird, I had no clue what was going on. Thanks for the help.

I was wondering which versions of the typings we should submit to DefinitelyTyped since the versioning scheme of Thunderbird is not linear. With non-linear, I mean that a new stable 115.x.y releases are interleaved with the beta 12[0-9].x.y releases.

Do we submit at least for the latest 115 version and then wait for the next big stable release? Or do we release for every version? 

DefinitelyTyped allows [subfolders for new major versions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#if-a-library-is-updated-to-a-new-major-version-with-breaking-changes-how-should-i-update-its-type-declaration-package), so we could create a new subfolder for each major version of Thunderbird

Example for [chai v2](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/chai/v2).

**Comment by JimDanner** [comment]
> I was wondering which versions of the typings we should submit to DefinitelyTyped since the versioning scheme of Thunderbird is not linear. With non-linear, I mean that a new stable 115.x.y releases are interleaved with the beta 12[0-9].x.y releases.
> 
> Do we submit at least for the latest 115 version and then wait for the next big stable release? Or do we release for every version?

In practice, it seems the API changes little between Thunderbird versions. It may be most practical to keep updating for the main, current version (for example, when i first published last year it was for the then-current version 109). Differentiating would not make a lot of difference other than perhaps confusing a few people.

I will take a good look at what changed in the last year, solve any remaining issues, and then publish the definition file for TB 115.

**Comment by JimDanner** [comment]
The update for Thunderbird 127 (the latest development version) is done, and it was [pulled into DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69922).

In future there may indeed be a need for two versions, as some extensions will conform to Manifest v2 and others to [Manifest v3](https://developer.thunderbird.net/add-ons/manifest-v3). I'll see if your suggestion of subfolders is the best way to organize it.
